# Generated by Django 3.2 on 2021-04-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록날짜'),
        ),
    ]
