# Generated by Django 3.1 on 2021-04-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cafe_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='subphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
