# Generated by Django 3.1 on 2021-04-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210414_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='insta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
